### ISSUE TITLE
filter code

### ISSUE THREAD

**Issue by Popperelay** [selfshadow/ltc_code#1]
Hello, where can I find the filter code of light source texture? Thanks a lot!

**Comment by selfshadow** [comment]
There's experimental code in the "texture" branch. The implementation is a little different than what is described in the paper, since the irradiance vector is used as the lookup direction, which eliminates the need for a filter border. It also uses a texture array to store the different blurred versions, rather than the MIPs of a 2D texture.

**Comment by Popperelay** [comment]
Get it. Thanks so much!
