### ISSUE TITLE
WebGL Demo links out of date

### ISSUE THREAD

**Issue by natevm** [selfshadow/ltc_code#4]
Hello!

First, thanks for the awesome work on LTC! Very cool!

I noticed there seem to be three different versions of the WebGL demos, which is causing me a little grief when using them as an implementation reference.

One's here:
https://blog.selfshadow.com/sandbox/ltc.html

Which is linked to from here: https://blogs.unity3d.com/2016/05/26/real-time-polygonal-light-shading-with-linearly-transformed-cosines/

That version uses 
```
mat3 Minv = mat3(
            vec3(  1,   0, t.y),
            vec3(  0, t.z,   0),
            vec3(t.w,   0, t.x)
        );
```

Then there are the demos linked to by the readme on this repository which are here:
https://blog.selfshadow.com/ltc/webgl/ltc_quad.html

Those use the following for MinV:
```
mat3 Minv = mat3(
            vec3(t1.x,  0, t1.y),
            vec3(  0, t1.z,   0),
            vec3(t1.w,  0, t2.x)
        );
```

Then finally there is the official implementation implemented within the WebGL folder of this repository, which use this for MinV:

```
mat3 Minv = mat3(
            vec3(t1.x, 0, t1.y),
            vec3(  0,  1,    0),
            vec3(t1.z, 0, t1.w)
        );
```

This is really confusing. I ran into an issue where I was using the newer lookup table from this repository with an out of date linear transformation scheme from the Unity blog post. Is there a way we could get these three sets of WebGL demos updated and consistent?

**Comment by selfshadow** [comment]
> First, thanks for the awesome work on LTC! Very cool!

Thanks!

The WebGL demo, BGFX-based demo and reference fitting code that are linked to in the Unity post  should all be consistent with one another and represent a snapshot in time when the paper was published. I don't think it makes sense to update these, since then they will diverge too much from the paper itself, but perhaps we can add a link to the GitHub repository.

The repository is intended as an evolving reference, with changes that reflect current best practice (a more accurate edge integral, a different matrix normalisation that's more numerically stable, a slightly different LUT parameterisation...) as well as additions, such as the line and disk lights that come from followup work.

I can see now that it was wishful thinking on my part that people would look at the commit history and see that changes had been made to the LUT format. I'll update the readme to document this and the other changes.

> Then there are the demos linked to by the readme on this repository which are here:

Sorry for the confusion here. I obviously forgot to update the linked demos when I made changes to the repository. I'll fix that shortly.

> Those use the following for MinV:

Just to be clear, it's `Minv` as in the inverse of M, not `MinV`, the minimum of some variable V. :)

**Comment by natevm** [comment]
That makes sense. I think so long as the demos linked by the readme are updated, and perhaps with a note that the lookup table changed, that should be a good enough hint for anyone trying to implement LTC in their own projects.

Thanks!
