### ISSUE TITLE
Some Confuse about fit code 

### ISSUE THREAD

**Issue by panyuanzhi** [selfshadow/ltc_code#6]
Hello,I recnetly read your paper "Real-Time Polygonal-Light Shading with Linearly Transformed Cosines" and your code, I have some confusions about the implements of the fit code.

1.why the matrix M in implement  is diffrent from in the paper? The matrix M in implements is like this ,
![M_Code](https://user-images.githubusercontent.com/12220654/89987097-071e4300-dcb0-11ea-8956-35cbd1689dbe.png)
and the matrix M in the paper is like this 
![paper_M](https://user-images.githubusercontent.com/12220654/89987285-611f0880-dcb0-11ea-8371-368c2c65272f.jpg)

2. what's  the meaning of the vector X Y Z 
![XYZ](https://user-images.githubusercontent.com/12220654/89987363-8ad82f80-dcb0-11ea-988d-b4311b760e24.png)

3.why the function eval implemented is diffrent from the paper?
![D](https://user-images.githubusercontent.com/12220654/89987603-ea363f80-dcb0-11ea-8070-7dd7ac8e427e.png).why the res is divided by Jacobian howerver the paper says it should be multiplied by Jacobian 
![paper_D](https://user-images.githubusercontent.com/12220654/89987821-3b463380-dcb1-11ea-8fbc-40a31b491cce.png)

Thank you for your reply.

**Comment by selfshadow** [comment]
Hi,

1. The implementation here has diverged from what is described in the paper. This is one of the changes that the note on the front page is alluding to when it says "The Linearly Transformed Cosine (LTC) tables in this implementation differ in their parameterisation and storage compared to the original paper". We made changes for accuracy and performance reasons. 

2. These are just the axes of a rotation matrix. They're updated here:
https://github.com/selfshadow/ltc_code/blob/master/fit/fitLTC.cpp#L238-L243

3. It's calculating the inverse Jacobian and dividing rather than multiplying. As such, it's equivalent, but I agree that this could be simplified. It's something I had meant to clean up a while ago but forgot about.

**Comment by panyuanzhi** [comment]
Hello,
          These days I read your paper and code again and agian.Now, I think I maybe  undstand your LTCs method.
  For the question above,
-  Q1,Q2.  Is the m11 m22 in the matrix M  meaning scaling and the m13 meaning the skewness? The rotation matrix mat3(X,Y,Z) is not the parameters to be optimized, and it is just for better and faster fit the brdf*cos(theta). According to my understanding,the matrix M to be optimized also can have 9 free degree,but it is too slow. Is it right?

- Q3. I got it.

Thanks a lot.

**Comment by selfshadow** [comment]
Actually regarding 1, I was referring to the final storage, whereas I see now that you're talking about a different location in the code. I think this submatrix is sparser since those were the only terms that had a significant impact on the fit, but the final matrix can still follow the cross form of the paper due to the rotation matrix [X Y Z].

**Comment by selfshadow** [comment]
Ahh, it looks as though my second reply came at the same time as yours. Yes, regarding 1 and 2, that's correct. We didn't find a benefit to adding more degrees of freedom and in fact it could have made the fitting worse (could get stuck in local minima).

It sounds as though things are clear now, so I will close this ticket.

**Comment by panyuanzhi** [comment]
ok, Thanks.
